BankLedgerMVC/BankLedgerMVC/Models/Transaction.cs
using System;

namespace BankLedgerMVC.Models
{
    public class Transaction
    {
        public Transaction() {}
        public Transaction(string AccountNumber, string TransactionType, decimal Amount) {
            this.Date = DateTime.Now;
            this.AccountNumber = AccountNumber;
            this.TransactionType = TransactionType;
            this.Amount = Amount;
        }
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string AccountNumber { get; set; }
        public string TransactionType { get; set; }
        public decimal Amount { get; set; }
    }
}

BankLedgerMVC/BankLedgerMVC/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BankLedgerMVC.Clients;
using System.Web.Mvc;
using BankLedgerMVC.Models;

namespace BankLedgerMVC.Controllers
{
    public class BankController : Controller
    {
        private static AccountClient accountClient = new AccountClient("http://localhost:8080");
        private static TransactionClient transactionClient = new TransactionClient("http://localhost:8080");

        public ActionResult Index()
        {
            if (IsLoggedIn()) {
                var account = getLoggedIn();
                return View(account);
            }
            return View();
        }

        public ActionResult VerifyLogin(string username, string password) {
            var accountList = accountClient.GetAccounts();

            if (IsLoggedIn())
            {
                @ViewBag.Message = "Account is already logged in. Please log out before logging into another account.";
            }

            var validLogIn = (from account in accountList
                              where account.UserName.Equals(username) && account.Password.Equals(password)
                              select account);
            if (!validLogIn.Any())
            {
                return View("Index");
            }
            else
            {
                Account newLogin = validLogIn.First();
                newLogin.LoggedIn = true;
                Console.WriteLine(newLogin.ToString());
                accountClient.UpdateAccount(newLogin);
                return View("Index", newLogin);
            }            
        }

        public ActionResult CreateAccount()
        {
            return View();
        }

        public ActionResult VerifyCreate(string accountNumber, string name, string username, string password) {
            var accountList = accountClient.GetAccounts();
            var isLoggedIn = (from account in accountList
                              where account.LoggedIn
                              select account);
            foreach (Account account in isLoggedIn)
            {
                account.LoggedIn = false;
                accountClient.UpdateAccount(account);
            }

            var x = (from account in accountList
                     where account.UserName.Equals(username) || account.AccountNumber.Equals(accountNumber)
                     select account.AccountNumber);

            if (x.Any())
            {
                @ViewBag.Message = "Account Number or Username already exists";
                return View("CreateAccount");
            }

            Account newAccount = new Account
            {
                AccountNumber = accountNumber,
                Name = name,
                UserName = username,
                Password = password,
                Balance = 0
            };
            accountClient.AddAccount(newAccount);
            return View("Index", newAccount);
        }

        public ActionResult Logout() {
            var accountList = accountClient.GetAccounts();

            var isLoggedIn = (from account in accountList
                              where account.LoggedIn
                              select account);
            foreach (Account account in isLoggedIn)
            {
                account.LoggedIn = false;
                accountClient.UpdateAccount(account);
            }
            return View("Index");
        }

        public ActionResult Transaction()
        {
            if (!IsLoggedIn()) {
                return View("Index");
            } else {
                var account = getLoggedIn();
                return View(account);
            }
            
        }
        
        public ActionResult VerifyTransaction(string transactionAmount, string transactionType) {
            var accountList = accountClient.GetAccounts();

            if (!IsLoggedIn())
            {
                return View("Index");
            }

            var currLogIn = (from account in accountList where account.LoggedIn select account).First();

            try
            {
                decimal amount = Decimal.Parse(transactionAmount);
                
                if (transactionType.Equals("Withdraw"))
                {
                    if (currLogIn.Balance - amount < 0)
                    {
                        @ViewBag.Message = "Invalid Amount Entered. Please try again";
                        return View("Transaction", currLogIn);
                    }
                    currLogIn.Balance -= amount;
                }
                else if (transactionType.Equals("Deposit"))
                {
                    currLogIn.Balance += amount;
                }
                else
                {
                    @ViewBag.Message = "Invalid input. Please try again.";
                    return View("Transaction", currLogIn);
                }
                accountClient.UpdateAccount(currLogIn);

                var transactionList = transactionClient.GetTransactions();
                transactionClient.AddTransaction(new Transaction
                {
                    Id = transactionList.Count(),
                    Date = DateTime.Now,
                    AccountNumber = currLogIn.AccountNumber,
                    TransactionType = transactionType,
                    Amount = amount
                });
                @ViewBag.Success = true;
                @ViewBag.Message = String.Format("Transaction successful!\n{0} amount of {1} from account {2}.\nNew balance is {3}",
                                                transactionType,
                                                amount,
                                                currLogIn.AccountNumber,
                                                currLogIn.Balance);
                return View("Transaction", currLogIn);
            } catch (FormatException) {
                @ViewBag.Message = "Invalid Amount Entered. Please try again";
                return View("Transaction", currLogIn);
            }
        }

        public ActionResult CheckBalance()
        {
            var accountList = accountClient.GetAccounts();

            if (!IsLoggedIn())
            {
                return View("Index");
            }

            var currLogIn = (from account in accountList where account.LoggedIn select account).First();
            return View("Index", currLogIn);
        }

        public ActionResult TransactionHistory()
        {
            var accountList = accountClient.GetAccounts();

            if (!IsLoggedIn())
            {
                return View("Index");
            }

            var currLogIn = (from account in accountList where account.LoggedIn select account).First();
            var transactionList = transactionClient.GetTransactions();

            var transactions = (from transaction in transactionList
                                where transaction.AccountNumber.Equals(currLogIn.AccountNumber)
                                select transaction);
            if (!transactions.Any())
            {
                return View();
            }
            else
            {
                TransactionViewModel transactionViewModel =
                                new TransactionViewModel(currLogIn, transactions.ToList());
                return View(transactionViewModel);
            }
        }

        private bool IsLoggedIn()
        {
            var accountList = accountClient.GetAccounts();
            var isLoggedIn = (from account in accountList
                              where account.LoggedIn
                              select account.AccountNumber);
            if (isLoggedIn.Any())
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        private Models.Account getLoggedIn()
        {
            var accountList = accountClient.GetAccounts();

            if (!IsLoggedIn())
            {
                return null;
            }
            else
            {
                return (from account in accountList where account.LoggedIn select account).First();
            }
        }
    }
}

BankLedgerMVC/BankLedgerMVC/Views/Bank/CreateAccount.cshtml
@{
    ViewData["Title"] = "Create Account";
}

<h3>@ViewData["Message"]</h3>

<form method="POST" action="@Url.Action("VerifyCreate", "Bank")">
    <h3>Create New Account</h3>
    <label>Account Number:</label>
    <input type="text" name="AccountNumber"><br>
    <label>Full Name:</label>
    <input type="text" name="Name"><br>
    <label>User Name:</label>
    <input type="text" name="UserName"><br>
    <label>Password:</label>
    <input type="text" name="Password"><br>
    <input type="submit">
</form>

BankLedgerMVC/BankLedgerMVC/Views/Bank/Index.cshtml
@model BankLedgerMVC.Models.Account

@{
    ViewData["Title"] = "Index";
}

<h2>Welcome to America's Greatest Bank</h2>
<h2>@ViewData["Message"]</h2>

@if (@Model != null) {
    <h4>Name: @Model.Name</h4>
    <h4>Account Number: @Model.AccountNumber</h4>
    <h4>Username: @Model.UserName</h4>
    <h4>Balance: @Model.Balance</h4>
}

else {
    <form method="POST" action="@Url.Action("VerifyLogin", "Bank")">
        <h3>Login:</h3>
        <label>username:</label>
        <input type="text" name="Username"><br>
        <label>password:</label>
        <input type="text" name="Password"><br>
        <input type="submit">
    </form>
}

BankLedgerMVC/BankLedgerMVC/Views/Bank/Transaction.cshtml
@model BankLedgerMVC.Models.Account
@{
    ViewData["Title"] = "Transaction";
}

<h3>@ViewData["Message"]</h3>

@if (@Model != null)
{
    <div class="container">
        <h4>Name: @Model.Name</h4>
        <h4>Username: @Model.UserName</h4>
        <h4>Available Balance: $@Model.Balance</h4>
    </div>
}

<form method="POST" action="@Url.Action("VerifyTransaction", "Bank")">
    <label>Amount: $</label>
    <input type="text" name="TransactionAmount"><br>
    <label>Transaction:</label>
    <select name="TransactionType">
        <option value="Withdraw">Withdraw</option>
        <option value="Deposit">Deposit</option>
    </select><br>
    <input type="submit">
</form>

BankLedgerMVC/BankLedgerMVC/Views/Bank/TransactionHistory.cshtml
@model BankLedgerMVC.Models.TransactionViewModel
@{
    ViewData["Title"] = "Transaction History";
}

@if (@Model != null) {
    <h3>Account Information</h3>
    <h4>Name: @Model.TransactionAccount.Name</h4>
    <h4>Account Number: @Model.TransactionAccount.AccountNumber</h4>
    <h4>Username: @Model.TransactionAccount.UserName</h4>
    <h4>Balance: @Model.TransactionAccount.Balance</h4>

    <h3>Transaction History</h3>
    for (int i=0; i<@Model.Transactions.Count; i++) {
        <div>
            <ol>
                <li>Transaction #@(i+1)</li>
                <li>Date: @Model.Transactions[i].Date</li>
                <li>Transaction Type: @Model.Transactions[i].TransactionType</li>
                <li>Amount: $@Model.Transactions[i].Amount</li>
            </ol>
        </div>
    }
}